# Generated by Django 3.0.6 on 2020-06-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='tagimage',
        ),
    ]
