# Generated by Django 3.0.6 on 2020-06-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_tagmodel_tagimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.PostsModel')),
            ],
        ),
    ]
