# Generated by Django 3.0.6 on 2020-06-06 03:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200604_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='null', editable=False, populate_from='user'),
        ),
    ]
