# Generated by Django 3.0.6 on 2020-06-06 03:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_postsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user'),
        ),
    ]
