# Generated by Django 3.0.6 on 2020-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_topfive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topfive',
            name='clicks',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
