# Generated by Django 3.0.6 on 2020-06-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200609_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopFive',
        ),
    ]
