# Generated by Django 3.0.6 on 2020-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_commentmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='posts',
        ),
    ]
