# Generated by Django 3.0.6 on 2020-06-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_tagmodel_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='articles.TagModel'),
        ),
    ]
