# Generated by Django 3.0.6 on 2020-06-07 11:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_postsmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='null', editable=False, populate_from=models.CharField(max_length=50)),
            preserve_default=False,
        ),
    ]
