# Generated by Django 3.0.6 on 2020-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200607_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmodel',
            name='slug',
        ),
    ]
