# Generated by Django 3.0.6 on 2020-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_tagmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='tagimage',
            field=models.ImageField(default='/uploads/404.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='picture',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/%H/%M'),
        ),
    ]
