# Generated by Django 3.0.6 on 2020-06-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200607_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='articles.TagModel'),
        ),
    ]
