# Generated by Django 3.0.6 on 2020-06-10 10:34

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='uploads/image/%Y/%m/%d')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', slugify=userinfo.models.custom_slugify)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
