# Generated by Django 3.0.6 on 2020-06-04 05:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='user.username'),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='avatar',
            field=models.ImageField(upload_to='uploads/image/%Y/%m/%d'),
        ),
    ]
