# Generated by Django 3.0.6 on 2020-06-06 03:33

import autoslug.fields
from django.db import migrations
import userinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20200604_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user', slugify=userinfo.models.custom_slugify),
        ),
    ]
