# Generated by Django 3.0.6 on 2020-06-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniRegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('country', models.CharField(max_length=30, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uniranking.UniRegionModel')),
            ],
        ),
        migrations.CreateModel(
            name='UniRankingByYearModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_display', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('year', models.SmallIntegerField()),
                ('ranking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniranking.RankingSystemModel')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniranking.UniversityModel')),
            ],
        ),
    ]
