# Generated by Django 3.0.6 on 2020-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unirankingbyyearmodel',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unirankingbyyearmodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
